Albergues/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('inventories.urls', namespace='inventories'))
]

inventories/urls.py
from django.conf.urls import url

from .views import create_refuge, index, sign_in, sign_out, sign_up, CreateRefugeAPIView, CreatePostAPIView

urlpatterns = [
    url(r'^sig-up/$', sign_up, name='sign-up'),
    url(r'^sign-in/$', sign_in, name='sign-in'),
    url(r'^sign-out/$', sign_out, name='sign-out'),
    url(r'^registrar/$', create_refuge, name='create-refuge'),
    url(r'^create-refuge/$', CreateRefugeAPIView.as_view(), name='create-refuge-api'),
    url(r'^create-post/$', CreatePostAPIView.as_view(), name='create-post-api'),
    url(r'^', index, name='index'),
]

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css"
          integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='//code.jquery.com/jquery-1.9.1.min.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/services/refuge.js' %}"></script>
    <script src="{% static 'js/controllers/refuge.js' %}"></script>
</head>
<body ng-app="fronterApp">

    <header>
        <nav class="navbar navbar-fixed-top navbar-light navbar-dark bg-inverse">
            <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'inventories:index' %}"><strong>Inicio</strong></a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'inventories:sign-up' %}"><strong>Registrarse</strong></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'inventories:sign-in' %}"><strong>Iniciar Sesión</strong></a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#"><strong>Mi refugio</strong></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'inventories:sign-out' %}"><strong>Cerrar Sesión</strong></a>
                    </li>
                {% endif %}
            </ul>

        </nav>
    </header>

    <section class="container m-t-3 p-t-2">
        {% block content %}{% endblock %}
    </section>

    <footer class="m-t-3 bg-inverse">

    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
            integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
     integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"
        integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlT8MXLzwQ7Dn--UXpwkMCMhOOtAI1ero&callback=initMap">
    </script>
</body>
</html>